## This is a conda environment file.
## Use it as follows:
##
##    conda env create -f environment-latestsage.yml
##
## See https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533
## or    https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
name: sage-cgf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - sage
  - setuptools_scm
  - sphinx
  - sphinxcontrib-websupport
  - sphinxcontrib-bibtex
  - lrslib
  - mathjax
  - pip
  - pip:
    - sage-package
